### PR TITLE
QA-2167 - Added the missing command center endpoints

### PR DESCRIPTION
**Pull request by benSlaughter**
### Details
Added endpoints for /commandcenter
Added /brandwatch command center endpoints
Minor updates of comment typos etc

Ran rubocop and rspec

### CODE REVIEW

**Comment by benSlaughter** [comment]
@jonathanchrisp could you take a look over this please

**Comment by bw-lee** [comment]
:+1:

**Comment by benSlaughter** [comment]
@jonathanchrisp addressed your comments
ready for review

**Comment by jonathanchrisp** [comment]
LGTM - Merging :+1:

**Pull request merged**
