### PR TITLE
ENT-1554 Add lock queries endpoint

### PR DESCRIPTION
**Pull request by Vitor-Carvalho**
This PR will add the new endpoint which allows users to lock/unlock queries.

Rubocop:
148 files inspected, no offenses detected

 [5] pry(main)>bw.unlock_query(457,352)
=> {"id"=>352,
 "name"=>"1010",
 "description"=>"",
 "creationDate"=>"2015-06-26T15:37:50.233+0000",
 "lastModificationDate"=>"2015-07-13T09:17:06.597+0000",
 "industry"=>"general-(recommended)",
 "includedTerms"=>["1010"],
 "excludedTerms"=>[],
 "contextTerms"=>[],
 "languages"=>["en"],
 "averageMonthlyMentions"=>278,
 "twitterLimit"=>1500,
 "dailyLimit"=>10000,
 "type"=>"search string",
 "twitterScreenName"=>nil,
 "highlightTerms"=>["1010"],
 "links"=>
  {"lastSevenDaysSentiment"=>"http://bond:8880/projects/457/data/volume/queries/sentiment.json?access_token=18eaf2b2-49fd-4029-8f58-b0bfbc6428af&queryId=352&startDate=2015-07-08T13:33:16.121Z&endDate=2015-07-15T13:33:16.121Z",
   "lastSevenDaysVolume"=>"http://bond:8880/projects/457/data/volume/queries/days.json?access_token=18eaf2b2-49fd-4029-8f58-b0bfbc6428af&queryId=352&startDate=2015-07-08T13:33:16.121Z&endDate=2015-07-15T13:33:16.121Z",
   "lastTenMentions"=>"http://bond:8880/projects/457/data/mentions.json?access_token=18eaf2b2-49fd-4029-8f58-b0bfbc6428af&queryId=352&startDate=2015-07-08T13:33:16.120Z&endDate=2015-07-15T13:33:16.120Z&page=0&pageSize=10&orderBy=id&orderDirection=desc"},
 "samplePercent"=>100,
 "lastModifiedUsername"=>"u=vitor@brandwatch.com",
 "languageAgnostic"=>false,
 "lockedQuery"=>false,
 "lockedByUsername"=>nil,
 "lockedTime"=>nil}

[6] pry(main)> bw.lock_query(457,352)
=> {"id"=>352,
 "name"=>"1010",
 "description"=>"",
 "creationDate"=>"2015-06-26T15:37:50.233+0000",
 "lastModificationDate"=>"2015-07-13T09:17:06.597+0000",
 "industry"=>"general-(recommended)",
 "includedTerms"=>["1010"],
 "excludedTerms"=>[],
 "contextTerms"=>[],
 "languages"=>["en"],
 "averageMonthlyMentions"=>278,
 "twitterLimit"=>1500,
 "dailyLimit"=>10000,
 "type"=>"search string",
 "twitterScreenName"=>nil,
 "highlightTerms"=>["1010"],
 "links"=>
  {"lastSevenDaysSentiment"=>"http://bond:8880/projects/457/data/volume/queries/sentiment.json?access_token=18eaf2b2-49fd-4029-8f58-b0bfbc6428af&queryId=352&startDate=2015-07-08T13:34:03.145Z&endDate=2015-07-15T13:34:03.145Z",
   "lastSevenDaysVolume"=>"http://bond:8880/projects/457/data/volume/queries/days.json?access_token=18eaf2b2-49fd-4029-8f58-b0bfbc6428af&queryId=352&startDate=2015-07-08T13:34:03.146Z&endDate=2015-07-15T13:34:03.146Z",
   "lastTenMentions"=>"http://bond:8880/projects/457/data/mentions.json?access_token=18eaf2b2-49fd-4029-8f58-b0bfbc6428af&queryId=352&startDate=2015-07-08T13:34:03.144Z&endDate=2015-07-15T13:34:03.144Z&page=0&pageSize=10&orderBy=id&orderDirection=desc"},
 "samplePercent"=>100,
 "lastModifiedUsername"=>"u=vitor@brandwatch.com",
 "languageAgnostic"=>false,
 "lockedQuery"=>true,
 "lockedByUsername"=>"u=vitor@brandwatch.com",
 "lockedTime"=>"2015-07-15T13:34:03.137+0000"}

### CODE REVIEW

**Comment by Vitor-Carvalho** [comment]
@jonathanchrisp , @benSlaughter : could you have a look at this one, please?

**Comment by jonathanchrisp** [comment]
This PR looks good, waiting for tests to run...

**Comment by Vitor-Carvalho** [comment]
Had to do some changes on this. I've updated the PR.
@jonathanchrisp @benSlaughter : could you please review this and merge it as soon as possible,please? I really need this one merged to finish some UI tests. Thanks

**Comment by benSlaughter** [comment]
Looks like there are merge conflicts

**Comment by Vitor-Carvalho** [comment]
@benSlaughter : Fixed it ;)

**Pull request merged**
