### PR TITLE
ENT-940 Adding usage by query endpoint

### PR DESCRIPTION
**Pull request by Vitor-Carvalho**
This PR will add the GET /admin/client/{clientId}/usagebyquery endpoint

Rubocop:
148 files inspected, no offenses detected

### CODE REVIEW

**Comment by Vitor-Carvalho** [comment]
@jonathanchrisp 
I've created this new PR to add an endpoint that was missing. 
Could you please review this one?
Thanks

**Comment by benSlaughter** [comment]
@Vitor-Carvalho you will need to require and include this new module
please see here: https://github.com/jonathanchrisp/bwapi/blob/master/lib/bwapi/client/admin.rb#L1

**Comment by Vitor-Carvalho** [comment]
@benSlaughter : thanks..I've updated the PR. This should be OK now

**Comment by jonathanchrisp** [comment]
LGTM :+1: @benSlaughter?

**Comment by bw-lee** [comment]
LGTM to  :+1:

**Pull request merged**
