### PR TITLE
ENT-939_Add_pricing_upgrades_enpoint

### PR DESCRIPTION
**Pull request by Vitor-Carvalho**
This PR will add the endpoint for GET /admin/pricingupgrades/{clientId} which will be used to test the upgrade clients feature on /Administration

Rubocop
149 files inspected, no offenses detected

### CODE REVIEW

**Comment by Vitor-Carvalho** [comment]
@jonathanchrisp : could you please have a look on this? It's a small addition of a missing endpoint

**Comment by Vitor-Carvalho** [comment]
@benSlaughter , @jonathanchrisp : can any of you look at this, please?

**Comment by jonathanchrisp** [comment]
LGTM :+1: @benSlaughter seconds review and merge if ok

**Comment by jonathanchrisp** [comment]
Merging

**Pull request merged**
