### PR TITLE
Adding a timeout to the request options configuration for Faraday

### PR DESCRIPTION
**Pull request by benSlaughter**
### Details

- Added open timeout option to BWAPI and added it into the request options for Faraday
- Added timeout option to BWAPI and added it into the request options for Faraday

### Results

```
154 files inspected, no offenses detected

148 examples, 0 failures
1797 / 2264 LOC (79.37%) covered.
```

### CODE REVIEW

**Comment by leemcgeever** [comment]
LGTM 👍

**Comment by jonathanchrisp** [comment]
Hey @benSlaughter, don't usually add new versions in feature PR's but all good for this time.

**Comment by jonathanchrisp** [comment]
@benSlaughter - merged, let me know how the pre release gem works and then we can publish this officially.

**Comment by benSlaughter** [comment]
@jonathanchrisp I did this in a separate commit as there is a bit of a chicken and egg issue with pre releases and versioning

**Pull request merged**
